"""Convert markdown audit / stress-test reports into professional-style PDFs."""
from __future__ import annotations

import re
from pathlib import Path
from fpdf import FPDF


# ─── 颜色常量 ────────────────────────────────────────────────────────────────
NAVY       = (7,  12, 44)
INDIGO     = (99, 120, 255)
ACCENT     = (108, 92, 231)
WHITE      = (255, 255, 255)
LIGHT_GRAY = (220, 225, 240)
GRAY       = (140, 158, 200)
RED_SOFT   = (239, 68,  68)
GREEN_SOFT = (34,  197, 94)
YELLOW     = (234, 179, 8)
TEXT_DARK  = (30,  40,  80)
ROW_ALT    = (240, 243, 255)

# 分数颜色
def score_color(score: int):
    if score >= 80:
        return (34, 197, 94)
    if score >= 60:
        return (59, 130, 246)
    if score >= 40:
        return (234, 179, 8)
    return (239, 68, 68)


def score_label(score: int) -> str:
    if score >= 80:
        return "Excellent"
    if score >= 60:
        return "Good"
    if score >= 40:
        return "Caution"
    return "Risk"


def _safe(text: str) -> str:
    """将不在 latin-1 范围内的字符替换为 ASCII 等价物"""
    replacements = {
        "\u2026": "...", "\u2018": "'",  "\u2019": "'",
        "\u201c": '"',   "\u201d": '"',  "\u2013": "-",
        "\u2014": "--",  "\u2022": "*",  "\u2713": "OK",
        "\u26a0": "[!]", "\u2714": "OK", "\ufe0f": "",
        "\u274c": "[X]", "\u2705": "[v]","u2728": "*",
        "\u2764": "<3",  "\U0001f512": "[lock]",
        "\U0001f4cb": "", "\U0001f4ca": "", "\U0001f4c4": "",
        # 新增常用 emoji
        "\U0001f6e1": "[shield]",  # 🛡
        "\U0001f517": "[link]",    # 🔗
        "\u2705": "[v]",           # ✅
        "\u274c": "[X]",           # ❌
        "\u26a0": "[!]",           # ⚠️
        "\U0001f50d": "[search]",  # 🔍
        "\U0001f527": "[wrench]",  # 🔧
        "\U0001f4cb": "",          # 📋
        "\u2699": "[gear]",        # ⚙
        "\U0001f4c4": "",          # 📄
        "\U0001f511": "[key]",     # 🔑
        "\U0001f3c6": "[trophy]",  # 🏆
        "\U0001f510": "[lock]",    # 🔐
        "\U0001f50f": "[lock]",    # 🔏
        # Stress test report emojis
        "\u26a1": "[zap]",         # ⚡
        "\U0001f4be": "[disk]",    # 💾
        "\U0001f504": "[cycle]",   # 🔄
        "\U0001f198": "[SOS]",     # 🆘
        "\U0001f9ea": "[test]",    # 🧪
        "\U0001f4c8": "[chart]",   # 📈
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # 兜底：去掉其余无法编码的字符（含 emoji）
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class AuditPDF(FPDF):
    def __init__(self, header_title: str = "Security Audit Report"):
        super().__init__()
        self._header_title = header_title
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    # ── 页眉 ──────────────────────────────────────────────────────────────────
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 18, "F")
        self.set_y(4)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*INDIGO)
        self.cell(0, 10, f"Health AI  |  {self._header_title}", align="L")
        self.set_text_color(*GRAY)
        self.set_font("Helvetica", "", 8)
        self.set_xy(0, 6)
        self.cell(0, 6, f"Page {self.page_no()}", align="R")
        self.set_y(22)

    # ── 页脚 ──────────────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*INDIGO)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 6, "Generated by Health AI  --  healthai.manta.network", align="C")

    # ── 章节标题 ──────────────────────────────────────────────────────────────
    def section_title(self, text: str):
        self.ln(4)
        self.set_fill_color(*INDIGO)
        self.rect(20, self.get_y(), 3, 7, "F")
        self.set_x(25)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*NAVY)
        self.cell(0, 7, _safe(text), ln=True)
        self.ln(2)

    # ── 子章节标题（### 级别） ────────────────────────────────────────────────
    def subsection_title(self, text: str):
        self.ln(2)
        self.set_font("Helvetica", "B", 9.5)
        self.set_text_color(*INDIGO)
        self.cell(0, 6, _safe(text), ln=True)
        self.ln(1)

    # ── 普通段落 ──────────────────────────────────────────────────────────────
    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*TEXT_DARK)
        self.multi_cell(0, 5.5, _safe(text))
        self.ln(1)

    # ── 分数大卡片行 ──────────────────────────────────────────────────────────
    def score_cards(self, scores: dict[str, int]):
        keys = list(scores.items())
        # 每行 3 个
        for row_start in range(0, len(keys), 3):
            row = keys[row_start:row_start + 3]
            card_w = (170) / 3
            x0 = 20
            y0 = self.get_y()
            card_h = 24
            for i, (label, val) in enumerate(row):
                cx = x0 + i * (card_w + 2)
                color = score_color(val)
                # 背景
                self.set_fill_color(245, 247, 255)
                self.set_draw_color(*color)
                self.set_line_width(0.6)
                self.rect(cx, y0, card_w, card_h, "FD")
                # 分数
                self.set_font("Helvetica", "B", 18)
                self.set_text_color(*color)
                self.set_xy(cx, y0 + 2)
                self.cell(card_w, 12, str(val), align="C")
                # 标签
                self.set_font("Helvetica", "", 7.5)
                self.set_text_color(*GRAY)
                self.set_xy(cx, y0 + 14)
                self.cell(card_w, 5, label, align="C")
                # 等级
                self.set_font("Helvetica", "B", 7)
                self.set_text_color(*color)
                self.set_xy(cx, y0 + 18)
                self.cell(card_w, 5, score_label(val), align="C")
            self.set_y(y0 + card_h + 4)

    # ── 表格 ─────────────────────────────────────────────────────────────────
    def draw_table(self, headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None):
        total_w = 170
        if col_widths is None:
            w = total_w / len(headers)
            col_widths = [w] * len(headers)

        # 表头
        self.set_fill_color(*NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 8)
        self.set_draw_color(*LIGHT_GRAY)
        self.set_line_width(0.2)
        for i, (h, cw) in enumerate(zip(headers, col_widths)):
            self.cell(cw, 7, _safe(h), border=1, fill=True)
        self.ln()

        # 数据行
        self.set_font("Helvetica", "", 7.5)
        for row_i, row in enumerate(rows):
            if self.get_y() > 265:
                self.add_page()
            fill = row_i % 2 == 1
            self.set_fill_color(*ROW_ALT)
            self.set_text_color(*TEXT_DARK)
            # 多行自适应高度
            max_lines = 1
            for cell_text, cw in zip(row, col_widths):
                lines = self.get_string_width(_safe(str(cell_text))) / (cw - 2)
                max_lines = max(max_lines, int(lines) + 1)
            row_h = min(max_lines * 4.5, 18)
            for cell_text, cw in zip(row, col_widths):
                txt = _safe(str(cell_text))
                # 截断过长内容
                while self.get_string_width(txt) > cw - 2 and len(txt) > 4:
                    txt = txt[:-1]
                if txt != _safe(str(cell_text)):
                    txt = txt[:-2] + ".."
                self.cell(cw, row_h, txt, border=1, fill=fill)
            self.ln()
        self.ln(3)

    # ── Recommendation 条目 ───────────────────────────────────────────────────
    def rec_item(self, text: str, idx: int):
        text = _safe(text)
        y = self.get_y()
        # 序号圆圈
        self.set_fill_color(*INDIGO)
        self.ellipse(20, y + 0.5, 5, 5, "F")
        self.set_xy(20, y)
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*WHITE)
        self.cell(5, 6, str(idx), align="C")
        # 内容
        self.set_x(27)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*TEXT_DARK)
        self.multi_cell(163, 5.5, text)
        self.ln(1)


# ─── 解析 Markdown ────────────────────────────────────────────────────────────

def _extract_between(text: str, start_marker: str, end_markers: list[str]) -> str:
    """提取两个 ## 标题之间的内容（行级匹配，防止 ### 被误判为 ## 边界）"""
    idx = text.find(start_marker)
    if idx < 0:
        return ""
    content = text[idx + len(start_marker):]
    for em in end_markers:
        # 加换行前缀，确保只在行首匹配 ## 标题
        needle = "\n" + em
        ei = content.find(needle)
        if ei >= 0:
            content = content[:ei]
    return content.strip()


def _parse_table(block: str) -> tuple[list[str], list[list[str]]]:
    """解析 Markdown 表格，自动跳过分隔行（| --- | :---: | 等）"""
    lines = [l.strip() for l in block.strip().splitlines() if l.strip().startswith("|")]
    if len(lines) < 2:
        return [], []
    headers = [c.strip() for c in lines[0].strip("|").split("|")]
    rows = []
    for line in lines[1:]:
        cells = [c.strip() for c in line.strip("|").split("|")]
        # 跳过分隔行：每个 cell 都是 --- / :---: 之类
        if cells and all(re.match(r"^\s*:?-+:?\s*$", c) for c in cells):
            continue
        rows.append(cells)
    return headers, rows


def _parse_scores(text: str) -> dict[str, int]:
    """从 ## Risk Scores 表格中解析各维度分数（新格式：Markdown table）"""
    block = _extract_between(text, "## Risk Scores", ["## ", "---"])
    scores = {}

    # 维度名映射（去掉 emoji 后小写匹配）
    dimension_map = {
        "overall security": "Overall",
        "overall":          "Overall",
        "privacy":          "Privacy",
        "privilege":        "Privilege",
        "integrity":        "Integrity",
        "supply chain":     "Dependency Risk",
        "dependency risk":  "Dependency Risk",
        "stability":        "Stability",
        # 兼容旧报告中可能存在的旧维度名
        "memory footprint": "Memory",
        "token cost":       "Token",
    }

    for line in block.splitlines():
        if not line.strip().startswith("|"):
            continue
        # 跳过分隔行
        cells = [c.strip() for c in line.strip("|").split("|")]
        if all(re.match(r"^\s*:?-+:?\s*$", c) for c in cells):
            continue
        if len(cells) < 2:
            continue

        dim_raw = cells[0]  # e.g. "🔏 Privacy" or "🏆 **Overall Security**"
        score_raw = cells[1]  # e.g. "100/100" or "**94/100**"

        # 提取数字分数
        score_m = re.search(r"(\d+)/100", score_raw)
        if not score_m:
            continue
        val = int(score_m.group(1))

        # 去掉 markdown 粗体符号和 emoji（latin-1 兜底），再小写匹配
        dim_clean = re.sub(r"\*+", "", dim_raw)  # 去掉 **
        dim_clean = dim_clean.encode("ascii", errors="ignore").decode("ascii")  # 去掉 emoji
        dim_clean = dim_clean.strip().lower()

        label = None
        for key, mapped in dimension_map.items():
            if key in dim_clean:
                label = mapped
                break

        if label:
            scores[label] = val

    return scores


def _parse_checklist_sections(text: str) -> list[tuple[str, list[str], list[list[str]]]]:
    """
    解析 ## 🔍 Detailed Security Checklist 下的所有 ### 子章节。
    返回列表: [(subsection_title, headers, rows), ...]
    """
    block = _extract_between(text, "## 🔍 Detailed Security Checklist", ["## "])
    if not block:
        # 兼容没有 emoji 的旧格式
        block = _extract_between(text, "## Detailed Security Checklist", ["## "])
    if not block:
        return []

    results = []
    # 按 ### 分割
    parts = re.split(r"\n(###\s+.+)", block)
    # parts[0] 是前言文字，之后交替：标题 / 内容
    i = 1
    while i < len(parts) - 1:
        sub_title = parts[i].lstrip("#").strip()
        sub_body  = parts[i + 1] if i + 1 < len(parts) else ""
        headers, rows = _parse_table(sub_body)
        if headers and rows:
            results.append((sub_title, headers, rows))
        i += 2

    return results


# ─── Stress Test PDF 生成 ─────────────────────────────────────────────────────

def _parse_stress_scores(md: str) -> dict[str, int]:
    """Parse five-dimension scores from stress test report markdown."""
    scores: dict[str, int] = {}
    dimension_map = {
        "stability": "Stability",
        "performance": "Performance",
        "resource": "Resource",
        "consistency": "Consistency",
        "recovery": "Recovery",
    }
    for line in md.splitlines():
        if not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if all(re.match(r"^\s*:?-+:?\s*$", c) for c in cells):
            continue
        if len(cells) < 2:
            continue
        dim_raw = cells[0]
        score_m = re.search(r"(\d+)/100", cells[1])
        if not score_m:
            continue
        dim_clean = re.sub(r"\*+", "", dim_raw)
        dim_clean = dim_clean.encode("ascii", errors="ignore").decode("ascii").strip().lower()
        for key, mapped in dimension_map.items():
            if key in dim_clean:
                scores[mapped] = int(score_m.group(1))
                break

    # Parse overall score
    overall_m = re.search(r"Overall Score[^\d]*(\d+)/100", md, re.I)
    if overall_m:
        scores["Overall"] = int(overall_m.group(1))
    elif not scores.get("Overall"):
        vals = [v for k, v in scores.items() if k != "Overall"]
        if vals:
            scores["Overall"] = round(sum(vals) / len(vals))

    return scores


def _parse_stress_metrics(md: str) -> dict[str, str]:
    """Parse key performance metrics from the stress test summary.

    Supports both list format (- Key: Value) and table format (| Key | Value |).
    """
    metrics: dict[str, str] = {}

    # ── Table format: parse from ## Test Configuration and ## Performance Metrics ──
    for section_name in ["## Test Configuration", "## Performance Metrics"]:
        block = _extract_between(md, section_name, ["## "])
        if block:
            for line in block.splitlines():
                if not line.strip().startswith("|"):
                    continue
                cells = [c.strip() for c in line.strip("|").split("|")]
                if len(cells) < 2:
                    continue
                if all(re.match(r"^\s*:?-+:?\s*$", c) for c in cells):
                    continue
                key = re.sub(r"\*+", "", cells[0]).strip()
                val = re.sub(r"\*+", "", cells[1]).strip()
                if not key or key.lower() in ("metric", "item", "value", "status"):
                    continue
                # Normalize key names
                key_lower = key.lower()
                if "test runs" in key_lower:
                    metrics["Test Runs"] = val
                elif "concurrency" in key_lower:
                    metrics["Concurrency"] = val
                elif "skill" in key_lower:
                    metrics["Skill"] = val
                elif "success rate" in key_lower:
                    # e.g. "10/10 (100.0%)" → extract parts
                    m = re.search(r"(\d+)/(\d+)\s*\(([^)]+)\)", val)
                    if m:
                        metrics["Total Runs"] = m.group(2)
                        metrics["Successes"] = m.group(1)
                        metrics["Success Rate"] = m.group(3).strip()
                elif "avg duration" in key_lower:
                    metrics["Avg Duration"] = val
                elif "p95 duration" in key_lower:
                    metrics["P95 Duration"] = val
                elif "min duration" in key_lower:
                    metrics["Min Duration"] = val
                elif "max duration" in key_lower:
                    metrics["Max Duration"] = val
                elif "std deviation" in key_lower:
                    metrics["Std Deviation"] = val

    # ── Fallback: list format (- Key: Value) ──
    if "Total Runs" not in metrics:
        m = re.search(r"(?:Total Runs|总次数):\s*(\d+)", md)
        if m:
            metrics["Total Runs"] = m.group(1)
    if "Successes" not in metrics:
        m = re.search(r"(?:Successes|成功次数):\s*(\d+)\s*\(([^)]+)\)", md)
        if m:
            metrics["Successes"] = m.group(1)
            metrics["Success Rate"] = m.group(2).strip()
    if "Avg Duration" not in metrics:
        m = re.search(r"(?:Avg Duration|平均耗时):\s*([\d.]+)s", md)
        if m:
            metrics["Avg Duration"] = m.group(1) + "s"
    if "P95 Duration" not in metrics:
        m = re.search(r"(?:P95 Duration|P95\s*耗时):\s*([\d.]+)s", md)
        if m:
            metrics["P95 Duration"] = m.group(1) + "s"
    if "Test Runs" not in metrics:
        m = re.search(r"(?:Test Runs|测试轮次)\*?\*?:\s*(\d+)", md)
        if m:
            metrics["Test Runs"] = m.group(1)
    if "Concurrency" not in metrics:
        m = re.search(r"(?:Concurrency|并发度)\*?\*?:\s*(\d+)", md)
        if m:
            metrics["Concurrency"] = m.group(1)
    m = re.search(r"Command:\s*`([^`]+)`", md)
    if m:
        metrics["Command"] = m.group(1)
    return metrics


def _generate_stress_pdf(md: str, out_path: Path) -> None:
    """Generate a professional PDF for a Stress Test report."""
    pdf = AuditPDF(header_title="Stress Test Report")
    pdf.add_page()

    # ── Cover block ──
    pdf.set_fill_color(*NAVY)
    pdf.rect(20, 22, 170, 36, "F")
    pdf.set_fill_color(*INDIGO)
    pdf.rect(20, 22, 4, 36, "F")

    pdf.set_xy(26, 26)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 12, "Skill Stress Test Report", ln=True)

    gen_match = re.search(r"Generated[：:]\s*(\S+)", md)
    gen_date = gen_match.group(1)[:19].replace("T", "  ") if gen_match else ""
    pdf.set_x(26)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*LIGHT_GRAY)
    pdf.cell(0, 6, f"Generated:  {gen_date}", ln=True)

    fn_match = re.search(r"file_name.*?:\s*(.+)", md, re.I)
    badge_text = fn_match.group(1).strip() if fn_match else ""
    if badge_text:
        pdf.set_x(26)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*INDIGO)
        pdf.cell(0, 7, f"[ {badge_text} ]")
    pdf.set_y(66)

    # ── Five-Dimension Scores ──
    scores = _parse_stress_scores(md)
    if scores:
        pdf.section_title("Five-Dimension Scores")
        overall = scores.pop("Overall", None)
        if overall is not None:
            color = score_color(overall)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*color)
            pdf.cell(0, 7, f"Overall Score: {overall}/100  ({score_label(overall)})", ln=True)
            pdf.ln(2)
        if scores:
            pdf.score_cards(scores)
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, "80-100 = Excellent   60-79 = Good   40-59 = Caution   <40 = Risk", ln=True)
        pdf.ln(3)

    # ── Test Configuration (table) ──
    metrics = _parse_stress_metrics(md)
    config_block = _extract_between(md, "## Test Configuration", ["## "])
    config_h, config_rows = _parse_table(config_block)
    if config_h and config_rows:
        pdf.section_title("Test Configuration")
        clean_h = [re.sub(r"\*+", "", h).strip() for h in config_h]
        clean_rows = [[re.sub(r"\*+", "", c).strip() for c in row] for row in config_rows]
        n = len(clean_h)
        widths = [60, 110] if n == 2 else [170 / n] * n
        pdf.draw_table(clean_h, clean_rows, widths)
    else:
        # Fallback: old list format
        config_keys = ["Test Runs", "Concurrency", "Command"]
        config_items = [(k, metrics[k]) for k in config_keys if k in metrics]
        if config_items:
            pdf.section_title("Test Configuration")
            headers = ["Item", "Value"]
            rows = [[k, v] for k, v in config_items]
            pdf.draw_table(headers, rows, [60, 110])

    # ── Performance Metrics (table with Status) ──
    perf_block = _extract_between(md, "## Performance Metrics", ["## "])
    perf_h, perf_rows = _parse_table(perf_block)
    if perf_h and perf_rows:
        pdf.section_title("Performance Metrics")
        # Clean markdown bold from cells
        clean_rows = []
        for row in perf_rows:
            clean_rows.append([re.sub(r"\*+", "", c).strip() for c in row])
        clean_h = [re.sub(r"\*+", "", h).strip() for h in perf_h]
        n = len(clean_h)
        if n == 3:
            widths = [60, 60, 50]
        else:
            widths = [170 / n] * n
        pdf.draw_table(clean_h, clean_rows, widths)
    else:
        # Fallback: old format
        perf_keys = ["Success Rate", "Avg Duration", "P95 Duration", "Total Runs", "Successes"]
        perf_items = {k: metrics[k] for k in perf_keys if k in metrics}
        if perf_items:
            pdf.section_title("Performance Metrics")
            headers = list(perf_items.keys())
            rows = [list(perf_items.values())]
            n = len(headers)
            widths = [170 / n] * n
            pdf.draw_table(headers, rows, widths)

    # ── Failure Samples ──
    failure_lines = re.findall(r"Run #(\d+)[\s(]*exit (\d+)[,)]\s*(?:duration\s*)?([\d.]+)s", md)
    if failure_lines:
        pdf.section_title("Failure Details")
        headers = ["Run #", "Exit Code", "Duration"]
        rows = [[f"#{r}", code, dur + "s"] for r, code, dur in failure_lines]
        pdf.draw_table(headers, rows, [30, 40, 100])

    # ── Assessment ──
    total_runs = int(metrics.get("Total Runs", "0") or "0")
    successes = int(metrics.get("Successes", "0") or "0")
    failures = total_runs - successes
    all_scores = list(scores.values()) + ([overall] if overall is not None else [])
    low_scores = [s for s in all_scores if s < 80]

    pdf.section_title("Assessment")
    if not low_scores and failures == 0:
        pdf.set_font("Helvetica", "", 9.5)
        pdf.set_text_color(*GREEN_SOFT)
        pdf.multi_cell(0, 5.5, _safe(
            "All dimensions scored 80 or above with zero failures. "
            "The skill demonstrates excellent stability and performance under stress testing conditions."
        ))
    else:
        recs = []
        if failures > 0:
            recs.append(f"{failures} failure(s) detected out of {total_runs} runs -- review failure logs for root cause.")
        for s_name, s_val in scores.items():
            if s_val < 80:
                recs.append(f"{s_name} score is {s_val}/100 (below 80) -- needs improvement.")
        if overall is not None and overall < 80:
            recs.append(f"Overall score is {overall}/100 -- consider addressing the issues above.")
        for i, r in enumerate(recs, 1):
            pdf.rec_item(r, i)
    pdf.ln(3)

    # ── Score Table (full) ──
    score_block = _extract_between(md, "## Five-Dimension Scores", ["## ", "---"])
    if not score_block:
        score_block = _extract_between(md, "## 五维度评分", ["## ", "---"])
    if score_block:
        score_h, score_rows = _parse_table(score_block)
        if score_h and score_rows:
            pdf.section_title("Score Breakdown")
            # Clean markdown formatting and emoji from dimension names
            clean_rows = []
            for row in score_rows:
                cleaned = []
                for cell in row:
                    c = re.sub(r"\*+", "", cell)  # strip **bold**
                    c = c.encode("ascii", errors="ignore").decode("ascii").strip()
                    cleaned.append(c)
                clean_rows.append(cleaned)
            n = len(score_h)
            widths = [170 / n] * n
            if n == 4:
                widths = [50, 30, 35, 55]
            elif n == 3:
                widths = [60, 40, 70]
            pdf.draw_table(score_h, clean_rows, widths)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out_path))


# ─── 主入口 ───────────────────────────────────────────────────────────────────

def generate_pdf(md_path: Path, out_path: Path, *, skill_type: str = "") -> None:
    md = md_path.read_text(encoding="utf-8")

    # Detect report type: explicit skill_type takes priority, fallback to content sniffing
    is_stress = (
        skill_type == "skill-stress-lab"
        or "Stress Lab" in md
        or "Stress Summary" in md
        or "Five-Dimension Scores" in md
        or "五维度评分" in md
    )
    if is_stress:
        _generate_stress_pdf(md, out_path)
        return

    pdf = AuditPDF()
    pdf.add_page()

    # ── 封面块 ────────────────────────────────────────────────────────────────
    # 大标题背景
    pdf.set_fill_color(*NAVY)
    pdf.rect(20, 22, 170, 36, "F")
    # 左侧彩条
    pdf.set_fill_color(*INDIGO)
    pdf.rect(20, 22, 4, 36, "F")

    pdf.set_xy(26, 26)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 12, "Skill Security Audit", ln=True)

    # 生成日期
    gen_match = re.search(r"Generated[：:]\s*(\S+)", md)
    gen_date  = gen_match.group(1)[:19].replace("T", "  ") if gen_match else ""
    pdf.set_x(26)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*LIGHT_GRAY)
    pdf.cell(0, 6, f"Generated:  {gen_date}", ln=True)

    # 文件名 badge
    fn_match = re.search(r"file_name.*?:\s*(.+)", md, re.I)
    badge_text = fn_match.group(1).strip() if fn_match else ""
    if badge_text:
        pdf.set_x(26)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*INDIGO)
        pdf.cell(0, 7, f"[ {badge_text} ]")
    pdf.set_y(66)

    # ── Security Verdict ──────────────────────────────────────────────────────
    verdict_block = _extract_between(md, "## Security Verdict", ["## "])
    verdict_text  = re.sub(r"###\s*", "", verdict_block).strip()
    if verdict_text:
        is_caution = "caution" in verdict_text.lower()
        bg = (255, 250, 235) if is_caution else (235, 255, 245)
        border_c = YELLOW if is_caution else GREEN_SOFT
        pdf.set_fill_color(*bg)
        pdf.set_draw_color(*border_c)
        pdf.set_line_width(0.8)
        pdf.rect(20, pdf.get_y(), 170, 12, "FD")
        pdf.set_x(24)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*border_c)
        pdf.cell(0, 12, _safe(verdict_text))
        pdf.ln(16)

    # ── Risk Scores ───────────────────────────────────────────────────────────
    scores = _parse_scores(md)
    if scores:
        pdf.section_title("Risk Scores")
        # Overall 单独展示，其余维度展示为卡片
        overall = scores.pop("Overall", None)
        if overall is not None:
            color = score_color(overall)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*color)
            pdf.cell(0, 7, f"Overall Security Score: {overall}/100  ({score_label(overall)})", ln=True)
            pdf.ln(2)
        if scores:
            pdf.score_cards(scores)
        # 图例
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, "80-100 = Excellent   60-79 = Good   40-59 = Caution   <40 = Risk", ln=True)
        pdf.ln(3)

    # ── Key Recommendations ────────────────────────────────────────────────────
    # 兼容新旧两种章节名
    rec_block = (_extract_between(md, "## 🔧 Key Recommendations", ["## "])
                 or _extract_between(md, "## Recommendations", ["## "]))
    recs = [l[1:].strip() for l in rec_block.splitlines() if l.strip().startswith("-")]
    if recs:
        pdf.section_title("Key Recommendations")
        for i, r in enumerate(recs, 1):
            pdf.rec_item(r, i)
        pdf.ln(2)

    # ── Detailed Security Checklist ────────────────────────────────────────────
    checklist_sections = _parse_checklist_sections(md)
    if checklist_sections:
        pdf.section_title("Detailed Security Checklist")
        # 列宽：# | Check Item | Status | Details
        default_widths_4 = [10, 95, 18, 47]
        default_widths_3 = [10, 110, 50]
        for sub_title, headers, rows in checklist_sections:
            pdf.subsection_title(sub_title)
            n = len(headers)
            if n == 4:
                widths = default_widths_4
            elif n == 3:
                widths = default_widths_3
            else:
                widths = [170 / n] * n
            pdf.draw_table(headers, rows, widths)

    # ── 兼容：旧格式的 Permission Overview（若存在） ────────────────────────────
    perm_block = _extract_between(md, "## Permission Overview", ["## "])
    perm_h, perm_rows = _parse_table(perm_block)
    if perm_h and perm_rows:
        pdf.section_title("Permission Overview")
        n = len(perm_h)
        widths = [170 / n] * n
        if n == 5:
            widths = [20, 32, 35, 22, 61]
        pdf.draw_table(perm_h, perm_rows, widths)

    # ── 兼容：旧格式的 Log Summary（若存在） ──────────────────────────────────
    log_block = _extract_between(md, "## Log Summary", ["## "])
    log_h, log_rows = _parse_table(log_block)
    if log_h and log_rows:
        pdf.section_title("Log Summary")
        n = len(log_h)
        widths = [60, 22, 18, 18, 52] if n == 5 else [170 / n] * n
        pdf.draw_table(log_h, log_rows, widths)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out_path))
