"""把 security_audit.md 转换成专业风格的 PDF 报告"""
from __future__ import annotations

import re
from pathlib import Path
from fpdf import FPDF


# ─── 颜色常量 ────────────────────────────────────────────────────────────────
NAVY       = (7,  12, 44)
INDIGO     = (99, 120, 255)
ACCENT     = (108, 92, 231)
WHITE      = (255, 255, 255)
LIGHT_GRAY = (220, 225, 240)
GRAY       = (140, 158, 200)
RED_SOFT   = (239, 68,  68)
GREEN_SOFT = (34,  197, 94)
YELLOW     = (234, 179, 8)
TEXT_DARK  = (30,  40,  80)
ROW_ALT    = (240, 243, 255)

# 分数颜色
def score_color(score: int):
    if score >= 80:
        return (34, 197, 94)
    if score >= 60:
        return (59, 130, 246)
    if score >= 40:
        return (234, 179, 8)
    return (239, 68, 68)


def score_label(score: int) -> str:
    if score >= 80:
        return "Excellent"
    if score >= 60:
        return "Good"
    if score >= 40:
        return "Fair"
    return "Needs Work"


def _safe(text: str) -> str:
    """将不在 latin-1 范围内的字符替换为 ASCII 等价物"""
    replacements = {
        "\u2026": "...", "\u2018": "'",  "\u2019": "'",
        "\u201c": '"',   "\u201d": '"',  "\u2013": "-",
        "\u2014": "--",  "\u2022": "*",  "\u2713": "OK",
        "\u26a0": "[!]", "\u2714": "OK", "\ufe0f": "",
        "\u274c": "[X]", "\u2705": "[v]","u2728": "*",
        "\u2764": "<3",  "\U0001f512": "[lock]",
        "\U0001f4cb": "", "\U0001f4ca": "", "\U0001f4c4": "",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    # 兜底：去掉其余无法编码的字符（含 emoji）
    return text.encode("latin-1", errors="ignore").decode("latin-1")


class AuditPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    # ── 页眉 ──────────────────────────────────────────────────────────────────
    def header(self):
        # 深色顶栏
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 18, "F")
        self.set_y(4)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*INDIGO)
        self.cell(0, 10, "Health AI  |  Security Audit Report", align="L")
        self.set_text_color(*GRAY)
        self.set_font("Helvetica", "", 8)
        self.set_xy(0, 6)
        self.cell(0, 6, f"Page {self.page_no()}", align="R")
        self.set_y(22)

    # ── 页脚 ──────────────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-14)
        self.set_draw_color(*INDIGO)
        self.set_line_width(0.3)
        self.line(20, self.get_y(), 190, self.get_y())
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 6, "Generated by Health AI  --  healthai.manta.network", align="C")

    # ── 章节标题 ──────────────────────────────────────────────────────────────
    def section_title(self, text: str):
        self.ln(4)
        self.set_fill_color(*INDIGO)
        self.rect(20, self.get_y(), 3, 7, "F")
        self.set_x(25)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*NAVY)
        self.cell(0, 7, _safe(text), ln=True)
        self.ln(2)

    # ── 普通段落 ──────────────────────────────────────────────────────────────
    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*TEXT_DARK)
        self.multi_cell(0, 5.5, _safe(text))
        self.ln(1)

    # ── 分数大卡片行 ──────────────────────────────────────────────────────────
    def score_cards(self, scores: dict[str, int]):
        keys = list(scores.items())
        # 每行 3 个
        for row_start in range(0, len(keys), 3):
            row = keys[row_start:row_start + 3]
            card_w = (170) / 3
            x0 = 20
            y0 = self.get_y()
            card_h = 24
            for i, (label, val) in enumerate(row):
                cx = x0 + i * (card_w + 2)
                color = score_color(val)
                # 背景
                self.set_fill_color(245, 247, 255)
                self.set_draw_color(*color)
                self.set_line_width(0.6)
                self.rect(cx, y0, card_w, card_h, "FD")
                # 分数
                self.set_font("Helvetica", "B", 18)
                self.set_text_color(*color)
                self.set_xy(cx, y0 + 2)
                self.cell(card_w, 12, str(val), align="C")
                # 标签
                self.set_font("Helvetica", "", 7.5)
                self.set_text_color(*GRAY)
                self.set_xy(cx, y0 + 14)
                self.cell(card_w, 5, label, align="C")
                # 等级
                self.set_font("Helvetica", "B", 7)
                self.set_text_color(*color)
                self.set_xy(cx, y0 + 18)
                self.cell(card_w, 5, score_label(val), align="C")
            self.set_y(y0 + card_h + 4)

    # ── 表格 ─────────────────────────────────────────────────────────────────
    def draw_table(self, headers: list[str], rows: list[list[str]], col_widths: list[float] | None = None):
        total_w = 170
        if col_widths is None:
            w = total_w / len(headers)
            col_widths = [w] * len(headers)

        # 表头
        self.set_fill_color(*NAVY)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 8)
        self.set_draw_color(*LIGHT_GRAY)
        self.set_line_width(0.2)
        for i, (h, cw) in enumerate(zip(headers, col_widths)):
            self.cell(cw, 7, _safe(h), border=1, fill=True)
        self.ln()

        # 数据行
        self.set_font("Helvetica", "", 7.5)
        for row_i, row in enumerate(rows):
            if self.get_y() > 265:
                self.add_page()
            fill = row_i % 2 == 1
            self.set_fill_color(*ROW_ALT)
            self.set_text_color(*TEXT_DARK)
            # 多行自适应高度
            max_lines = 1
            for cell_text, cw in zip(row, col_widths):
                lines = self.get_string_width(str(cell_text)) / (cw - 2)
                max_lines = max(max_lines, int(lines) + 1)
            row_h = min(max_lines * 4.5, 18)
            for cell_text, cw in zip(row, col_widths):
                txt = _safe(str(cell_text))
                # 截断过长内容
                while self.get_string_width(txt) > cw - 2 and len(txt) > 4:
                    txt = txt[:-1]
                if txt != _safe(str(cell_text)):
                    txt = txt[:-2] + ".."
                self.cell(cw, row_h, txt, border=1, fill=fill)
            self.ln()
        self.ln(3)

    # ── Recommendation 条目 ───────────────────────────────────────────────────
    def rec_item(self, text: str, idx: int):
        text = _safe(text)
        y = self.get_y()
        # 序号圆圈
        self.set_fill_color(*INDIGO)
        self.ellipse(20, y + 0.5, 5, 5, "F")
        self.set_xy(20, y)
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(*WHITE)
        self.cell(5, 6, str(idx), align="C")
        # 内容
        self.set_x(27)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*TEXT_DARK)
        self.multi_cell(163, 5.5, text)
        self.ln(1)


# ─── 解析 Markdown ────────────────────────────────────────────────────────────

def _extract_between(text: str, start_marker: str, end_markers: list[str]) -> str:
    """提取两个 ## 标题之间的内容（行级匹配，防止 ### 被误判为 ## 边界）"""
    idx = text.find(start_marker)
    if idx < 0:
        return ""
    content = text[idx + len(start_marker):]
    for em in end_markers:
        # 加换行前缀，确保只在行首匹配 ## 标题
        needle = "\n" + em
        ei = content.find(needle)
        if ei >= 0:
            content = content[:ei]
    return content.strip()


def _parse_table(block: str) -> tuple[list[str], list[list[str]]]:
    """解析 Markdown 表格"""
    lines = [l.strip() for l in block.strip().splitlines() if l.strip().startswith("|")]
    if len(lines) < 2:
        return [], []
    headers = [c.strip() for c in lines[0].strip("|").split("|")]
    rows = []
    for line in lines[2:]:  # 跳过分隔行
        row = [c.strip() for c in line.strip("|").split("|")]
        rows.append(row)
    return headers, rows


def _parse_scores(text: str) -> dict[str, int]:
    """从 ## Risk Scores 块解析分数"""
    block = _extract_between(text, "## Risk Scores", ["## ", "---"])
    scores = {}
    label_map = {
        "overall security score": "Overall",
        "privacy":    "Privacy",
        "privilege":  "Privilege",
        "memory footprint": "Memory",
        "token cost":  "Token",
        "stability":   "Stability",
    }
    for line in block.splitlines():
        m = re.match(r"-\s*(.+?):\s*(\d+)/100", line, re.I)
        if m:
            raw_label = m.group(1).strip().lower()
            val = int(m.group(2))
            label = label_map.get(raw_label, m.group(1).strip())
            scores[label] = val
    return scores


# ─── 主入口 ───────────────────────────────────────────────────────────────────

def generate_pdf(md_path: Path, out_path: Path) -> None:
    md = md_path.read_text(encoding="utf-8")

    pdf = AuditPDF()
    pdf.add_page()

    # ── 封面块 ────────────────────────────────────────────────────────────────
    # 大标题背景
    pdf.set_fill_color(*NAVY)
    pdf.rect(20, 22, 170, 36, "F")
    # 左侧彩条
    pdf.set_fill_color(*INDIGO)
    pdf.rect(20, 22, 4, 36, "F")

    pdf.set_xy(26, 26)
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(*WHITE)
    pdf.cell(0, 12, "Skill Security Audit", ln=True)

    # 生成日期
    gen_match = re.search(r"Generated[：:]\s*(\S+)", md)
    gen_date  = gen_match.group(1)[:19].replace("T", "  ") if gen_match else ""
    pdf.set_x(26)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*LIGHT_GRAY)
    pdf.cell(0, 6, f"Generated:  {gen_date}", ln=True)

    # 文件名 badge
    fn_match = re.search(r"file_name.*?:\s*(.+)", md, re.I)
    badge_text = fn_match.group(1).strip() if fn_match else ""
    if badge_text:
        pdf.set_x(26)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*INDIGO)
        pdf.cell(0, 7, f"[ {badge_text} ]")
    pdf.set_y(66)

    # ── Security Verdict ──────────────────────────────────────────────────────
    verdict_block = _extract_between(md, "## Security Verdict", ["## "])
    verdict_text  = re.sub(r"###\s*", "", verdict_block).strip()
    if verdict_text:
        is_caution = "caution" in verdict_text.lower()
        bg = (255, 250, 235) if is_caution else (235, 255, 245)
        border_c = YELLOW if is_caution else GREEN_SOFT
        pdf.set_fill_color(*bg)
        pdf.set_draw_color(*border_c)
        pdf.set_line_width(0.8)
        pdf.rect(20, pdf.get_y(), 170, 12, "FD")
        pdf.set_x(24)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(*border_c)
        pdf.cell(0, 12, _safe(verdict_text))
        pdf.ln(16)

    # ── Risk Scores ───────────────────────────────────────────────────────────
    scores = _parse_scores(md)
    if scores:
        pdf.section_title("Risk Scores")
        pdf.score_cards(scores)
        # 图例
        pdf.set_font("Helvetica", "", 7.5)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, "80-100 = Excellent   60-79 = Good   40-59 = Fair   <40 = Needs Work", ln=True)
        pdf.ln(3)

    # ── Recommendations ────────────────────────────────────────────────────────
    rec_block = _extract_between(md, "## Recommendations", ["## "])
    recs = [l[1:].strip() for l in rec_block.splitlines() if l.strip().startswith("-")]
    if recs:
        pdf.section_title("Recommendations")
        for i, r in enumerate(recs, 1):
            pdf.rec_item(r, i)
        pdf.ln(2)

    # ── Permission Overview ────────────────────────────────────────────────────
    perm_block = _extract_between(md, "## Permission Overview", ["## "])
    perm_h, perm_rows = _parse_table(perm_block)
    if perm_h and perm_rows:
        pdf.section_title("Permission Overview")
        # 列宽
        n = len(perm_h)
        widths = [170 / n] * n
        if n == 5:
            widths = [20, 32, 35, 22, 61]
        pdf.draw_table(perm_h, perm_rows, widths)

    # ── Memory Pattern Hits ────────────────────────────────────────────────────
    mem_block = _extract_between(md, "## Memory Pattern Hits", ["## "])
    mem_h, mem_rows = _parse_table(mem_block)
    if mem_h and mem_rows:
        pdf.section_title("Memory Pattern Hits")
        n = len(mem_h)
        widths = [30, 50, 90] if n == 3 else [170 / n] * n
        pdf.draw_table(mem_h, mem_rows, widths)

    # ── Log Summary ───────────────────────────────────────────────────────────
    log_block = _extract_between(md, "## Log Summary", ["## "])
    log_h, log_rows = _parse_table(log_block)
    if log_h and log_rows:
        pdf.section_title("Log Summary")
        n = len(log_h)
        widths = [60, 22, 18, 18, 52] if n == 5 else [170 / n] * n
        pdf.draw_table(log_h, log_rows, widths)

    # ── Log Pattern Hits ──────────────────────────────────────────────────────
    lpat_block = _extract_between(md, "## Log Pattern Hits", ["## "])
    lpat_h, lpat_rows = _parse_table(lpat_block)
    if lpat_h and lpat_rows:
        # 只展示前 30 行，避免 PDF 过长
        display_rows = lpat_rows[:30]
        pdf.section_title("Log Pattern Hits")
        if len(lpat_rows) > 30:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*GRAY)
            pdf.cell(0, 5, f"(Showing first 30 of {len(lpat_rows)} entries)", ln=True)
            pdf.ln(1)
        n = len(lpat_h)
        widths = [30, 55, 85] if n == 3 else [170 / n] * n
        pdf.draw_table(lpat_h, display_rows, widths)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(out_path))
